name: morfeo
description: "This app helps you to perform power naps!"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  alarm: ^4.0.11
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  health: ^11.1.0
  permission_handler: ^11.3.1
  pine: ^1.0.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
